services:
  - type: web
    name: my-finance-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
